"""
SITRUS ertriage package.

Core package for text normalization, feature extraction, entity retrieval,
and triage decision layer.
"""

from ertriage.config import (
    KonfigurasiTriase,
    STATUS_TERSERTIFIKASI,
    STATUS_PERLU_REVIEW,
    STATUS_TERINDIKASI,
    REASON_EXACT_MODEL_MATCH,
    REASON_HIGH_PROB_MATCH,
    REASON_BRAND_TIDAK_TERDETEKSI,
    REASON_BRAND_TIDAK_ADA_DI_DJID,
    REASON_MEREK_ADA_MODEL_TIDAK_DITEMUKAN,
    REASON_PROB_AMBIGU,
    FEATURES_PRODUCTION,
    FEATURES_EVALUABLE,
    MIN_MODEL_LENGTH,
    RANDOM_SEED,
)

__all__ = [
    "KonfigurasiTriase",
    "STATUS_TERSERTIFIKASI",
    "STATUS_PERLU_REVIEW",
    "STATUS_TERINDIKASI",
    "REASON_EXACT_MODEL_MATCH",
    "REASON_HIGH_PROB_MATCH",
    "REASON_BRAND_TIDAK_TERDETEKSI",
    "REASON_BRAND_TIDAK_ADA_DI_DJID",
    "REASON_MEREK_ADA_MODEL_TIDAK_DITEMUKAN",
    "REASON_PROB_AMBIGU",
    "FEATURES_PRODUCTION",
    "FEATURES_EVALUABLE",
    "MIN_MODEL_LENGTH",
    "RANDOM_SEED",
]
